name = "JuliaReactToDo"
uuid = "fcd050ab-f5af-4aca-ab91-7e4945df288a"
authors = ["kogad <kogad.ga@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
MySQL = "39abe10b-433b-5dbd-92d4-e302a9df00cd"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Tables = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
